export const STUDENTS_FETCH_START = 'STUDENTS_FETCH_START';
export const STUDENTS_FETCH_SUCCESS = 'STUDENTS_FETCH_SUCCESS';
export const STUDENTS_FETCH_ERROR = 'STUDENTS_FETCH_ERROR';

export const DELETE_STUDENT_START = 'DELETE_STUDENT_START';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_ERROR = 'DELETE_STUDENT_ERROR';
